[prod]
host01 ansible_host=host-ip ansible_user=root
host02 ansible_host=host-ip ansible_user=root
host03 ansible_host=host-ip ansible_user=root

[stage]
host01 ansible_host=host-ip ansible_user=root
host02 ansible_host=host-ip ansible_user=root
host03 ansible_host=host-ip ansible_user=root

[prod:vars]
new_user="ansible"
ssh_public_key="ssh-rsa AAAAB3NzaC1yc2EAAA... ваш ключ"

[stage:vars]
new_user="ansible"
ssh_public_key="ssh-rsa AAAAB3NzaC1yc2EAAA... ваш ключ"